-- item_taxes — global tax rule catalogue (e.g. "GST 5%").
create table item_taxes (
  id bigint generated by default as identity primary key,
  name text not null default '',
  rate numeric not null,
  inclusive boolean default false,
  description text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
alter table item_taxes enable row level security;

-- tax_groups — reusable bundles of item_taxes, e.g. "Standard GST".
create table tax_groups (
  id bigint generated always as identity primary key,
  name text not null,
  description text,
  combined_rate numeric(6,3) not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create trigger trg_tax_groups_updated_at
  before update on tax_groups
  for each row execute function set_updated_at();
alter table tax_groups enable row level security;
create policy "authenticated can read tax_groups" on tax_groups
  for select using (auth.role() = 'authenticated');

-- tax_group_members — join table: which item_taxes make up a tax_group.
create table tax_group_members (
  tax_group_id bigint not null references tax_groups(id) on delete cascade,
  item_tax_id bigint not null references item_taxes(id) on delete cascade,
  primary key (tax_group_id, item_tax_id)
);
alter table tax_group_members enable row level security;
create policy "authenticated can read tax_group_members" on tax_group_members
  for select using (auth.role() = 'authenticated');

-- Keeps tax_groups.combined_rate in sync with the sum of its members' rates.
create or replace function refresh_tax_group_combined_rate()
returns trigger as $$
declare
  affected_group bigint := coalesce(new.tax_group_id, old.tax_group_id);
begin
  update tax_groups
  set combined_rate = coalesce((
    select sum(it.rate) from tax_group_members m
    join item_taxes it on it.id = m.item_tax_id
    where m.tax_group_id = affected_group
  ), 0)
  where id = affected_group;
  return null;
end;
$$ language plpgsql;

create trigger trg_tax_group_members_refresh
  after insert or update or delete on tax_group_members
  for each row execute function refresh_tax_group_combined_rate();
