-- Baseline schema snapshot, hand-assembled from this repo's Alembic
-- history (migrations 0001-0004) and cross-verified column-by-column,
-- constraint-by-constraint, trigger-by-trigger against the live database
-- via information_schema/pg_catalog introspection (supabase db pull/dump
-- both require Docker, which isn't available on the machine this was
-- written on). Represents the exact live public-schema state as of
-- 2026-08-29 — this file is marked "applied" via
-- `supabase migration repair --status applied`, not actually executed,
-- since every object here already exists live.
--
-- public.alembic_version is intentionally excluded — it's Alembic's own
-- bookkeeping table, left alone and unrelated to Supabase-CLI-managed
-- schema going forward.
--
-- Two things worth knowing, preserved here exactly as found rather than
-- "fixed" (out of scope for this baseline):
--   - restaurants.shop_timings exists live even though migrations/versions/
--     0001_add_restaurants_table.py never created it — that file doesn't
--     fully reflect how the table was actually provisioned.
--   - currencies and item_taxes both have RLS enabled with zero policies
--     (locked to service_role only) — neither 0001 nor 0002 turned this on,
--     so it happened out-of-band, most likely a Supabase Dashboard default
--     from when they were created directly.

create extension if not exists pgcrypto;

-- ── shared trigger helper ────────────────────────────────────────────
create or replace function set_updated_at()
returns trigger as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql;

-- ── currencies ───────────────────────────────────────────────────────
create table currencies (
  code text primary key default 'INR',
  symbol text not null default '₹',
  created_at timestamptz not null default now()
);
alter table currencies enable row level security;

insert into currencies (code, symbol) values
  ('INR', '₹'), ('USD', '$'), ('EUR', '€'), ('GBP', '£'), ('AED', 'AED')
on conflict (code) do nothing;

-- ── item_taxes — global tax rule catalogue ──────────────────────────────
create table item_taxes (
  id bigint generated by default as identity primary key,
  name text not null default '',
  rate numeric not null,
  inclusive boolean default false,
  description text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
alter table item_taxes enable row level security;

-- ── tax_groups — reusable bundles of item_taxes ─────────────────────────
create table tax_groups (
  id bigint generated always as identity primary key,
  name text not null,
  description text,
  combined_rate numeric(6,3) not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create trigger trg_tax_groups_updated_at
  before update on tax_groups
  for each row execute function set_updated_at();
alter table tax_groups enable row level security;
create policy "authenticated can read tax_groups" on tax_groups
  for select using (auth.role() = 'authenticated');

create table tax_group_members (
  tax_group_id bigint not null references tax_groups(id) on delete cascade,
  item_tax_id bigint not null references item_taxes(id) on delete cascade,
  primary key (tax_group_id, item_tax_id)
);
alter table tax_group_members enable row level security;
create policy "authenticated can read tax_group_members" on tax_group_members
  for select using (auth.role() = 'authenticated');

create or replace function refresh_tax_group_combined_rate()
returns trigger as $$
declare
  affected_group bigint := coalesce(new.tax_group_id, old.tax_group_id);
begin
  update tax_groups
  set combined_rate = coalesce((
    select sum(it.rate) from tax_group_members m
    join item_taxes it on it.id = m.item_tax_id
    where m.tax_group_id = affected_group
  ), 0)
  where id = affected_group;
  return null;
end;
$$ language plpgsql;

create trigger trg_tax_group_members_refresh
  after insert or update or delete on tax_group_members
  for each row execute function refresh_tax_group_combined_rate();

-- ── restaurants ──────────────────────────────────────────────────────
create table restaurants (
  id uuid primary key default gen_random_uuid(),
  owner_id uuid not null,
  name text not null,
  description text,
  is_open boolean not null default true,
  currency varchar(10) not null default '₹',
  logo_url text,
  image_url text,
  address_line text,
  pincode varchar(20),
  city text,
  state text,
  country text not null default 'India',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  shop_timings json default '{}'::json
);
create index ix_restaurants_owner_id on restaurants (owner_id);
alter table restaurants
  add constraint fk_restaurants_owner_id foreign key (owner_id)
  references auth.users(id) on delete cascade;

-- ── dishes ───────────────────────────────────────────────────────────
create table dishes (
  id uuid primary key default gen_random_uuid(),
  restaurant_id uuid not null references restaurants(id) on delete cascade,
  name text not null,
  description text,
  base_price numeric(10,2) not null,
  currency_code text not null default 'INR' references currencies(code),
  category text not null,
  image_url text,
  available boolean not null default true,
  veg boolean not null default true,
  show_in_menu boolean not null default true,
  tag text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index idx_dishes_restaurant on dishes (restaurant_id);
create index idx_dishes_category on dishes (restaurant_id, category);
create trigger trg_dishes_updated_at
  before update on dishes
  for each row execute function set_updated_at();
alter table dishes enable row level security;
create policy "owner can manage own dishes" on dishes for all
  using (restaurant_id in (select id from restaurants where owner_id = auth.uid()))
  with check (restaurant_id in (select id from restaurants where owner_id = auth.uid()));

-- ── item_prices ──────────────────────────────────────────────────────
create table item_prices (
  id uuid primary key default gen_random_uuid(),
  dish_id uuid not null unique references dishes(id) on delete cascade,
  base_price numeric(10,2) not null,
  currency_code text not null references currencies(code),
  total_tax_amount numeric(10,2) not null default 0,
  final_price numeric(10,2) not null,
  mrp numeric(10,2),
  discount_type text,
  discount_on text,
  discount_value numeric(10,2),
  discount_label text,
  discount_valid_from timestamptz,
  discount_valid_until timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint chk_discount_consistent check (
    (discount_type is null and discount_on is null and discount_value is null)
    or (discount_type is not null and discount_on is not null and discount_value is not null)
  ),
  check (discount_type in ('percentage', 'fixed')),
  check (discount_on in ('basePrice', 'priceIncludingTaxes'))
);
create index idx_item_prices_dish on item_prices (dish_id);
create trigger trg_item_prices_updated_at
  before update on item_prices
  for each row execute function set_updated_at();
alter table item_prices enable row level security;
create policy "owner can manage own item_prices" on item_prices for all
  using (dish_id in (
    select id from dishes where restaurant_id in (select id from restaurants where owner_id = auth.uid())
  ))
  with check (dish_id in (
    select id from dishes where restaurant_id in (select id from restaurants where owner_id = auth.uid())
  ));

create or replace function sync_dish_base_price()
returns trigger as $$
begin
  update dishes
  set base_price = new.base_price, updated_at = now()
  where id = new.dish_id
    and base_price is distinct from new.base_price;
  return new;
end;
$$ language plpgsql;

create trigger trg_item_prices_sync_dish_base_price
  after insert or update of base_price on item_prices
  for each row execute function sync_dish_base_price();

-- ── tax_line_items ───────────────────────────────────────────────────
create table tax_line_items (
  id uuid primary key default gen_random_uuid(),
  item_price_id uuid not null unique references item_prices(id) on delete cascade,
  total_tax_amount numeric(10,2) not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create trigger trg_tax_line_items_updated_at
  before update on tax_line_items
  for each row execute function set_updated_at();
alter table tax_line_items enable row level security;
create policy "owner can manage own tax_line_items" on tax_line_items for all
  using (item_price_id in (
    select ip.id from item_prices ip
    join dishes d on d.id = ip.dish_id
    where d.restaurant_id in (select id from restaurants where owner_id = auth.uid())
  ))
  with check (item_price_id in (
    select ip.id from item_prices ip
    join dishes d on d.id = ip.dish_id
    where d.restaurant_id in (select id from restaurants where owner_id = auth.uid())
  ));

create table tax_line_item_groups (
  tax_line_item_id uuid not null references tax_line_items(id) on delete cascade,
  tax_group_id bigint not null references tax_groups(id) on delete restrict,
  computed_amount numeric(10,2) not null default 0,
  primary key (tax_line_item_id, tax_group_id)
);
alter table tax_line_item_groups enable row level security;
create policy "owner can manage own tax_line_item_groups" on tax_line_item_groups for all
  using (tax_line_item_id in (
    select tli.id from tax_line_items tli
    join item_prices ip on ip.id = tli.item_price_id
    join dishes d on d.id = ip.dish_id
    where d.restaurant_id in (select id from restaurants where owner_id = auth.uid())
  ))
  with check (tax_line_item_id in (
    select tli.id from tax_line_items tli
    join item_prices ip on ip.id = tli.item_price_id
    join dishes d on d.id = ip.dish_id
    where d.restaurant_id in (select id from restaurants where owner_id = auth.uid())
  ));

create table tax_line_item_taxes (
  tax_line_item_id uuid not null references tax_line_items(id) on delete cascade,
  item_tax_id bigint not null references item_taxes(id) on delete restrict,
  computed_amount numeric(10,2) not null default 0,
  primary key (tax_line_item_id, item_tax_id)
);
alter table tax_line_item_taxes enable row level security;
create policy "owner can manage own tax_line_item_taxes" on tax_line_item_taxes for all
  using (tax_line_item_id in (
    select tli.id from tax_line_items tli
    join item_prices ip on ip.id = tli.item_price_id
    join dishes d on d.id = ip.dish_id
    where d.restaurant_id in (select id from restaurants where owner_id = auth.uid())
  ))
  with check (tax_line_item_id in (
    select tli.id from tax_line_items tli
    join item_prices ip on ip.id = tli.item_price_id
    join dishes d on d.id = ip.dish_id
    where d.restaurant_id in (select id from restaurants where owner_id = auth.uid())
  ));

create or replace function refresh_tax_line_item_total()
returns trigger as $$
declare
  affected_line uuid := coalesce(new.tax_line_item_id, old.tax_line_item_id);
  new_total numeric(10,2);
  affected_price uuid;
begin
  select coalesce(sum(computed_amount), 0) into new_total from (
    select computed_amount from tax_line_item_groups where tax_line_item_id = affected_line
    union all
    select computed_amount from tax_line_item_taxes where tax_line_item_id = affected_line
  ) t;

  update tax_line_items set total_tax_amount = new_total, updated_at = now()
  where id = affected_line
  returning item_price_id into affected_price;

  update item_prices set total_tax_amount = new_total, updated_at = now()
  where id = affected_price;

  return null;
end;
$$ language plpgsql;

create trigger trg_tax_line_item_groups_refresh
  after insert or update or delete on tax_line_item_groups
  for each row execute function refresh_tax_line_item_total();
create trigger trg_tax_line_item_taxes_refresh
  after insert or update or delete on tax_line_item_taxes
  for each row execute function refresh_tax_line_item_total();

-- ── profiles ─────────────────────────────────────────────────────────
create table profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text,
  avatar_url text,
  is_active boolean not null default true,
  is_superuser boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create trigger trg_profiles_updated_at
  before update on profiles
  for each row execute function set_updated_at();
alter table profiles enable row level security;
create policy "users can view own profile" on profiles
  for select using (auth.uid() = id);
create policy "users can update own profile" on profiles
  for update using (auth.uid() = id) with check (auth.uid() = id);

create or replace function handle_new_user()
returns trigger as $$
begin
  insert into public.profiles (id, full_name, avatar_url)
  values (new.id, new.raw_user_meta_data ->> 'full_name', new.raw_user_meta_data ->> 'avatar_url');
  return new;
end;
$$ language plpgsql security definer set search_path = public;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function handle_new_user();
